### PR TITLE
Major Structural Improvements

### PR DESCRIPTION
**Pull request by TieniePritchard**
Fixed the bugs with the webcam not working on some PCs.

### CODE REVIEW

**Comment by Mistborn94** [comment]
It seems you do a lit of GUI building in the code. Isn't it better to just have fxml templates for the different screens, for the sake of maintainability?

These links might help:
- http://stackoverflow.com/questions/18619394/loading-new-fxml-in-the-same-scene
- https://blogs.oracle.com/acaicedo/entry/managing_multiple_screens_in_javafx1

**Comment by TieniePritchard** [comment]
I've restructured the application to work with the MVC architecture. Also, I've transformed it to FXML - you're right, it becomes a maintenance nightmare if FXML isn't used.

**Comment by ghost** [comment]
Ran it before merging. Camera stream only shows top right corner of whatever is in front of my camera. Also could you add some kind of feedback when it fails to connect to server?

**Comment by TieniePritchard** [comment]
The Canvas was cropping the webcam's stream - I've added a fix to that. Also, I've added throwing exceptions to server unavailability - it's propagated through the application correctly now and the application displays if the server is unavailable. Furthermore, I've added facial detection, and added exception handling for if it detects more than one face in the photo. Also, the photo is now cropped to the facial detection area.

**Comment by ghost** [comment]
Could you make it that the user can not attempt to login without giving input. Camera stream seems to be working now. Also delete the .idea and .gradle folder from the repo

**Comment by TieniePritchard** [comment]
Done

**Pull request merged**
